openapi: 3.0.1
info:
  title: vehicle
  version: 0.0.1
paths:
  /:
    post:
      requestBody:
        description: desc
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestRequest'
      responses:
        '200':
          description: desc
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
components:
  schemas:
    TestRequest:
      type: object
      properties:
        vehicle:
          $ref: '#/components/schemas/Vehicle'
      required:
        - vehicle
    TestResponse:
      type: object
      properties:
        vehicle:
          $ref: '#/components/schemas/Vehicle'
      required:
        - vehicle
    Vehicle:
      oneOf:
        - $ref: '#/components/schemas/Ship'
        - $ref: '#/components/schemas/Plane'
        - $ref: '#/components/schemas/Truck'
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          SHIP: '#/components/schemas/Ship'
          PLANE: '#/components/schemas/Plane'
          TRUCK: '#/components/schemas/Truck'
    BaseVehicle:
      type: object
      properties:
        weight:
          type: number
      required:
        - weight
    Ship:
      allOf:
        - $ref: '#/components/schemas/BaseVehicle'
        - type: object
          properties:
            sailLength:
              type: number
          required:
            - sailLength
    Plane:
      allOf:
        - $ref: '#/components/schemas/BaseVehicle'
        - type: object
          properties:
            passengerCount:
              type: number
          required:
            - passengerCount
    Truck:
      allOf:
        - $ref: '#/components/schemas/BaseVehicle'
        - type: object
          properties:
            maxCargoWeight:
              type: number
          required:
            - maxCargoWeight